name: rs2sv
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - cudatoolkit=11.8  # adjust/remove if using CPU
  - pip
  - pip:
      - lightning
      - hydra-core
      - omegaconf
      - einops
      - timm
      - numpy
      - pandas
      - matplotlib
      - scikit-image
      - opencv-python
      - pillow
      - rasterio
      - geopandas
      - shapely
      - pyproj
      - tqdm
      - tensorboard
      - wandb
      - dvc
      - pydantic
      - flake8
      - pytest
